#!/bin/bash
set -euo pipefail

# ── Prepare step: clean input PDB ──
run_stage_prepare() {
    local out="output/setup/complex_clean.pdb"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    mkdir -p output/setup
    echo "PREPARE: Cleaning input PDB..."

    local input="${PDB:-input/system.pdb}"
    if [ ! -f "$input" ]; then
        echo "ERROR: Input PDB not found: $input (set PDB in config.sh)"
        exit 1
    fi

    # Strip water only. Keep everything else (protein, DNA, structural ions).
    awk '
    /^ATOM|^HETATM/ {
        resname = substr($0,18,3)
        gsub(/ /,"",resname)
        if (resname == "HOH" || resname == "SOL" || resname == "WAT" || resname == "TIP3" || resname == "SPC") next
        print
    }
    /^TER|^END/ { print }
    ' "$input" > "$out"

    echo "PREPARE: $(grep -c '^ATOM\|^HETATM' "$out" 2>/dev/null || echo 0) atoms written"
}

# ── Topology generation ──
run_stage_topol() {
    local out="output/setup/processed.gro"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    mkdir -p output/setup
    echo "TOPOL: Generating topology..."

    # Run pdb2gmx from output/setup so include paths in generated
    # chain topologies are relative to that directory (avoids double
    # path like output/setup/output/setup/posre.itp)
    $GMX pdb2gmx \
        -f "$PWD/output/setup/complex_clean.pdb" \
        -o "$PWD/$out" \
        -p "$PWD/output/setup/topol.top" \
        -i "$PWD/output/setup/posre.itp" \
        -ff "$FORCEFIELD" \
        -water "$WATER_MODEL" \
        -ignh -missing -noter

    if [ ! -f "$out" ]; then
        echo "ERROR: pdb2gmx failed to produce $out"
        exit 1
    fi

    # Fix include paths in chain topology files — pdb2gmx may write
    # absolute-style paths that resolve incorrectly when the chain
    # topologies are in a subdirectory
    for itp in output/setup/topol_*.itp; do
        if [ -f "$itp" ]; then
            sed "s|#include \"output/setup/|#include \"|g" "$itp" > "$itp.tmp" 2>/dev/null
            mv "$itp.tmp" "$itp" 2>/dev/null || true
        fi
    done

    echo "TOPOL: Complete"
}

# ── Box definition ──
run_stage_box() {
    local out="output/setup/box.gro"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    echo "BOX: Creating $BOX_TYPE box..."
    $GMX editconf \
        -f output/setup/processed.gro \
        -o "$out" \
        -bt "$BOX_TYPE" \
        -d "$BOX_DISTANCE"

    [ -f "$out" ] || { echo "ERROR: editconf failed"; exit 1; }
    echo "BOX: Complete"
}

# ── Solvation ──
run_stage_solvate() {
    local out="output/setup/solv.gro"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    echo "SOLVATE: Adding water..."
    $GMX solvate \
        -cp output/setup/box.gro \
        -cs spc216.gro \
        -o "$out" \
        -p output/setup/topol.top

    [ -f "$out" ] || { echo "ERROR: solvate failed"; exit 1; }
    echo "SOLVATE: Complete"
}

# ── Ion addition ──
run_stage_ions() {
    local out="output/setup/ions.gro"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    echo "IONS: Adding ions..."
    mkdir -p output/setup

    $GMX grompp \
        -f mdp/em.mdp \
        -c output/setup/solv.gro \
        -r output/setup/solv.gro \
        -p output/setup/topol.top \
        -o output/setup/ions.tpr \
        -maxwarn 2

    echo "SOL" | $GMX genion \
        -s output/setup/ions.tpr \
        -o "$out" \
        -p output/setup/topol.top \
        -pname "$CATION" \
        -nname "$ANION" \
        -neutral \
        -conc "$SALT_CONC"

    [ -f "$out" ] || { echo "ERROR: genion failed"; exit 1; }
    echo "IONS: Complete"
}

# ── Index file creation ──
# Uses GROMACS' default index groups and combines them dynamically
# into the groups expected by the MDP temperature coupling lines
# (tc-grps = Protein_DNA Water_Ions).
#
# Rather than hardcoding group numbers (which vary by system), this
# function determines the current maximum group number from make_ndx
# output and assigns the next two numbers to the new groups.
run_stage_index() {
    local out="output/setup/index.ndx"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    echo "INDEX: Creating temperature coupling groups..."

    # Verify the auto-generated 'Water' and 'Ion' groups exist before
    # building selections. GROMACS creates them after solvation (solv.gro)
    # and ion addition (ions.gro). If either is missing, the selections
    # below would silently be wrong.
    local check
    check=$($GMX select -s output/setup/ions.gro \
        -select 'group Water; group Ion' -on "$out.check" 2>&1)
    rm -f "$out.check"
    if echo "$check" | grep -q "no such index group\|Cannot match"; then
        echo "ERROR: Required index groups 'Water' or 'Ion' not found."
        echo "       These are auto-generated by GROMACS after solvation"
        echo "       and ion addition. Check that output/setup/solv.gro"
        echo "       and output/setup/ions.gro exist and were created."
        exit 1
    fi

    # Generate the two temperature-coupling groups with gmx select.
    # Group names are expression-derived (deterministic), so we rename
    # them afterwards to the names the MDP tc-grps expect.
    $GMX select -s output/setup/ions.gro -on "$out" \
        -select 'not (group Water or group Ion); group Water or group Ion'

    [ -f "$out" ] || { echo "ERROR: index generation failed"; exit 1; }

    # Rename expression-derived group names to MDP-expected names
    awk '
    /^\[/ {
        if ($0 == "[ not_(group_Water_or_group_Ion) ]") print "[ Protein_DNA ]"
        else if ($0 == "[ group_Water_or_group_Ion ]") print "[ Water_Ions ]"
        else print
        next
    }
    { print }
    ' "$out" > "$out.tmp"
    mv "$out.tmp" "$out"

    # Verify the renamed groups exist
    if ! grep -q "Protein_DNA" "$out"; then
        echo "ERROR: Protein_DNA group not found after renaming."
        exit 1
    fi
    if ! grep -q "Water_Ions" "$out"; then
        echo "ERROR: Water_Ions group not found after renaming."
        exit 1
    fi

    echo "INDEX: Complete"
}

# ── Run grompp with strict warning verification ──
# Runs gmx grompp, then inspects every warning. Only the two known benign
# warnings are tolerated:
#   1. free ions not bound by a potential/constraint
#   2. COM removal in the presence of position restraints
# Any other warning, or grompp failure, exits with a clear error.
# Usage: run_grompp_checked <maxwarn> <grompp args...>
run_grompp_checked() {
    local maxwarn="$1"
    shift

    local log
    log=$(mktemp)

    $GMX grompp -maxwarn "$maxwarn" "$@" > "$log" 2>&1
    local rc=$?

    if [ "$rc" -ne 0 ]; then
        echo "ERROR: grompp failed:"
        grep -E 'Fatal|Error|NOTE|WARNING' "$log" 2>/dev/null | head -10
        rm -f "$log"
        exit 1
    fi

    # Inspect every warning block and verify it is expected
    local block="" bad=0
    while IFS= read -r line; do
        case "$line" in
            "NOTE "*|"WARNING "*)
                if [ -n "$block" ]; then
                    case "$block" in
                        *"not bound by a potential or constraint"*) ;;
                        *"Removing center of mass motion"*) ;;
                        *) echo "ERROR: Unexpected grompp warning:"; echo "$block"; bad=1 ;;
                    esac
                fi
                block="$line"
                ;;
            "  "*)
                [ -n "$block" ] && block="$block
$line"
                ;;
        esac
    done < "$log"

    if [ -n "$block" ]; then
        case "$block" in
            *"not bound by a potential or constraint"*) ;;
            *"Removing center of mass motion"*) ;;
            *) echo "ERROR: Unexpected grompp warning:"; echo "$block"; bad=1 ;;
        esac
    fi

    rm -f "$log"
    if [ "$bad" -ne 0 ]; then
        echo "       If this warning is expected for your system, review"
        echo "       the MDP and topology before proceeding."
        exit 1
    fi
}

# ── Energy minimization ──
run_stage_em() {
    local out="output/equilibration/em.gro"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    mkdir -p output/equilibration
    echo "EM: Energy minimization..."

    run_grompp_checked 0 \
        -f mdp/em.mdp \
        -c output/setup/ions.gro \
        -r output/setup/ions.gro \
        -p output/setup/topol.top \
        -n output/setup/index.ndx \
        -o output/equilibration/em.tpr

    $GMX mdrun \
        -deffnm output/equilibration/em \
        -v

    if [ ! -f "$out" ]; then
        echo "ERROR: EM failed to produce $out"
        exit 1
    fi

    # Verify convergence: GROMACS writes "converged to Fmax" to the log
    # when the minimization reaches the force tolerance (emtol).
    # The output .gro file is written even without convergence, so file
    # existence alone is insufficient.
    if ! grep -qi "converged" output/equilibration/em.log 2>/dev/null; then
        echo "ERROR: Energy minimization did not converge."
        echo "       Check output/equilibration/em.log for details."
        exit 1
    fi
    echo "EM: Converged"
}

# ── NVT equilibration ──
run_stage_nvt() {
    local out="output/equilibration/nvt.gro"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    echo "NVT: Temperature equilibration..."

    run_grompp_checked 2 \
        -f mdp/nvt.mdp \
        -c output/equilibration/em.gro \
        -r output/equilibration/em.gro \
        -p output/setup/topol.top \
        -n output/setup/index.ndx \
        -o output/equilibration/nvt.tpr

    local gpu_flags
    gpu_flags=$(gmx_gpu_flags)

    $GMX mdrun \
        -deffnm output/equilibration/nvt \
        -cpi output/equilibration/nvt.cpt \
        $gpu_flags \
        -v

    if [ ! -f "$out" ]; then
        echo "ERROR: NVT failed to produce $out"
        exit 1
    fi
    echo "NVT: Complete"
}

# ── NPT equilibration ──
run_stage_npt() {
    local out="output/equilibration/npt.gro"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    echo "NPT: Pressure equilibration..."

    run_grompp_checked 2 \
        -f mdp/npt.mdp \
        -c output/equilibration/nvt.gro \
        -r output/equilibration/nvt.gro \
        -t output/equilibration/nvt.cpt \
        -p output/setup/topol.top \
        -n output/setup/index.ndx \
        -o output/equilibration/npt.tpr

    local gpu_flags
    gpu_flags=$(gmx_gpu_flags)

    $GMX mdrun \
        -deffnm output/equilibration/npt \
        -cpi output/equilibration/npt.cpt \
        $gpu_flags \
        -v

    if [ ! -f "$out" ]; then
        echo "ERROR: NPT failed to produce $out"
        exit 1
    fi
    echo "NPT: Complete"
}

# ── Production MD (extend-from-checkpoint loop) ──
#
# The checkpoint (md.cpt) is the single source of truth. Each iteration:
#   1. Read current time from md.cpt (or 0 if absent)
#   2. Compute target = min(current_time + CHUNK_NS, PRODUCTION_NS)
#   3. Convert the TPR to end at target
#   4. Run mdrun (stopping at target or walltime, whichever comes first)
#   5. Re-read checkpoint to confirm progress
#
# The loop runs multiple chunks per PBS job when walltime allows.
# When the walltime budget is nearly exhausted, the job exits 0 so
# the scheduler (or manual re-submit) can continue with a fresh job.
# -maxh is ONLY a walltime safety mechanism — the target controls the end.
run_stage_production() {
    mkdir -p output/production
    echo "PRODUCTION: extend-from-checkpoint loop"

    # ── Lock: prevent concurrent production runs (corrupts md.cpt/xtc) ──
    local lock_dir="output/production/.production.lock"
    if command -v flock >/dev/null 2>&1; then
        exec 9>"$lock_dir.flock"
        if ! flock -n 9; then
            echo "PRODUCTION: another production job is active; skipping" >&2
            return 0
        fi
    else
        if ! mkdir "$lock_dir" 2>/dev/null; then
            # Lock exists — check if owner is still alive
            if [ -f "$lock_dir/pid" ]; then
                local old_pid
                old_pid=$(cat "$lock_dir/pid" 2>/dev/null || echo "")
                if [ -n "$old_pid" ] && ! kill -0 "$old_pid" 2>/dev/null; then
                    echo "PRODUCTION: removing stale lock (PID $old_pid dead)" >&2
                    rm -rf "$lock_dir"
                fi
            fi
            # Retry acquisition after potential stale removal
            if ! mkdir "$lock_dir" 2>/dev/null; then
                echo "PRODUCTION: another production job is active; skipping" >&2
                return 0
            fi
        fi
        echo "$$" > "$lock_dir/pid"
    fi
    trap 'rm -rf "$lock_dir" "$lock_dir.flock" 2>/dev/null; exec 9>&-' RETURN

    # ── Compile TPR on first use ──
    if [ ! -f output/production/md.tpr ]; then
        echo "PRODUCTION: compiling TPR..."
        run_grompp_checked 2 \
            -f "${MD_MDP:-mdp/md.mdp}" \
            -c output/equilibration/npt.gro \
            -r output/equilibration/npt.gro \
            -p output/setup/topol.top \
            -n output/setup/index.ndx \
            -o output/production/md.tpr
    fi

    # ── Guard: checkpoint lost mid-run (trajectory exists but no checkpoint) ──
    if [ ! -f output/production/md.cpt ] && [ -f output/production/md.xtc ]; then
        echo "ERROR: checkpoint missing but trajectory exists — data loss suspected" >&2
        echo "       Delete md.xtc and re-submit to start production from scratch." >&2
        return 1
    fi

    # ── Derived parameters ──
    local prod_ns_ps chunk_ns_ps dt job_wall_s safety_s gpu_flags
    dt=$(production_dt)
    prod_ns_ps=$(awk -v ns="$PRODUCTION_NS" 'BEGIN{printf "%.6f", ns*1000}')
    chunk_ns_ps=$(awk -v ns="$CHUNK_NS" 'BEGIN{printf "%.6f", ns*1000}')
    job_wall_s=$(walltime_to_seconds "$PROD_WALLTIME")
    safety_s=$(( job_wall_s / 20 )); [ "$safety_s" -lt 60 ] && safety_s=60
    gpu_flags=$(gmx_gpu_flags)

    # ── Current time from checkpoint ──
    local t
    t=$(checkpoint_time_ps output/production/md.cpt "$dt") || return 1

    if time_gte "$t" "$prod_ns_ps"; then
        production_mark_complete
        return 0
    fi

    # ── Walltime budget ──
    local job_start now elapsed remaining maxh
    job_start=$(date +%s)

    echo "PRODUCTION: starting loop (current=${t} ps, target=${prod_ns_ps} ps)"

    while :; do
        # Check walltime budget
        now=$(date +%s)
        elapsed=$(( now - job_start ))
        remaining=$(( job_wall_s - elapsed ))
        if [ "$remaining" -le "$safety_s" ]; then
            echo "PRODUCTION: walltime budget nearly exhausted (${remaining}s left); ending job"
            return 0
        fi

        # Compute next target
        local target
        target=$(time_min "$(awk -v a="$t" -v b="$chunk_ns_ps" 'BEGIN{printf "%.6f", a+b}')" "$prod_ns_ps")

        if time_lte "$target" "$t"; then
            echo "ERROR: cannot advance (target=${target} ps <= current=${t} ps)" >&2
            return 1
        fi

        # Maxh = 90% of remaining walltime (safety mechanism only)
        maxh=$(awk -v r="$remaining" 'BEGIN{h=(r*0.9)/3600; if(h<0.01) h=0.01; printf "%.3f", h}')

        echo "PRODUCTION: extending to ${target} ps (maxh=${maxh}h)"
        # Atomic TPR replacement: write to temp, then mv (never leave corrupted md.tpr)
        # GROMACS appends .tpr to -o filenames that lack the extension, so use .tpr suffix.
        local tmp_tpr="output/production/md.tpr.tmp.tpr"
        "$GMX" convert-tpr \
            -s output/production/md.tpr \
            -until "$target" \
            -o "$tmp_tpr" || {
            rm -f "$tmp_tpr"
            echo "ERROR: convert-tpr failed" >&2
            return 1
        }
        if [ ! -f "$tmp_tpr" ]; then
            echo "ERROR: convert-tpr exited 0 but $tmp_tpr not found" >&2
            return 1
        fi
        mv "$tmp_tpr" output/production/md.tpr

        # -append only if checkpoint exists (not first run)
        local append_flag=""
        [ -f output/production/md.cpt ] && append_flag="-append"

        "$GMX" mdrun \
            -deffnm output/production/md \
            -cpi output/production/md.cpt \
            $append_flag \
            -maxh "$maxh" \
            $gpu_flags \
            -v || {
            echo "ERROR: mdrun failed" >&2
            return 1
        }

        # Verify checkpoint was written
        if [ ! -f output/production/md.cpt ]; then
            echo "ERROR: mdrun exited without writing a checkpoint" >&2
            return 1
        fi

        # Re-read checkpoint time
        local new_t
        new_t=$(checkpoint_time_ps output/production/md.cpt "$dt") || return 1

        # Check completion
        if time_gte "$new_t" "$prod_ns_ps"; then
            production_mark_complete
            return 0
        fi

        # Zero progress detection
        if time_lte "$new_t" "$t"; then
            echo "ERROR: mdrun made no progress (t=${t} ps -> ${new_t} ps). Check walltime/GPU." >&2
            return 1
        fi

        # Did we reach the chunk target? If not, walltime safety hit.
        if time_lt "$new_t" "$target"; then
            echo "PRODUCTION: chunk hit walltime at ${new_t} ps (target was ${target} ps); ending job"
            return 0
        fi

        # Chunk completed — continue to next target
        t="$new_t"
    done
}

# ── Mark production complete (UI marker, not authoritative) ──
production_mark_complete() {
    touch output/production/PRODUCTION_COMPLETE
    echo "PRODUCTION: COMPLETE (${PRODUCTION_NS} ns reached)"
}
