#!/bin/bash
set -euo pipefail

# ── Prepare step: clean input PDB ──
run_stage_prepare() {
    local out="output/setup/complex_clean.pdb"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    mkdir -p output/setup
    echo "PREPARE: Cleaning input PDB..."

    local input="${PDB:-input/system.pdb}"
    if [ ! -f "$input" ]; then
        echo "ERROR: Input PDB not found: $input (set PDB in config.sh)"
        exit 1
    fi

    # Strip water only. Keep everything else (protein, DNA, structural ions).
    awk '
    /^ATOM|^HETATM/ {
        resname = substr($0,18,3)
        gsub(/ /,"",resname)
        if (resname == "HOH" || resname == "SOL" || resname == "WAT" || resname == "TIP3" || resname == "SPC") next
        print
    }
    /^TER|^END/ { print }
    ' "$input" > "$out"

    echo "PREPARE: $(grep -c '^ATOM\|^HETATM' "$out" 2>/dev/null || echo 0) atoms written"
}

# ── Topology generation ──
run_stage_topol() {
    local out="output/setup/processed.gro"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    mkdir -p output/setup
    echo "TOPOL: Generating topology..."

    # Run pdb2gmx from output/setup so include paths in generated
    # chain topologies are relative to that directory (avoids double
    # path like output/setup/output/setup/posre.itp)
    $GMX pdb2gmx \
        -f "$PWD/output/setup/complex_clean.pdb" \
        -o "$PWD/$out" \
        -p "$PWD/output/setup/topol.top" \
        -i "$PWD/output/setup/posre.itp" \
        -ff "$FORCEFIELD" \
        -water "$WATER_MODEL" \
        -ignh -missing -noter

    if [ ! -f "$out" ]; then
        echo "ERROR: pdb2gmx failed to produce $out"
        exit 1
    fi

    # Fix include paths in chain topology files — pdb2gmx may write
    # absolute-style paths that resolve incorrectly when the chain
    # topologies are in a subdirectory
    for itp in output/setup/topol_*.itp; do
        if [ -f "$itp" ]; then
            sed "s|#include \"output/setup/|#include \"|g" "$itp" > "$itp.tmp" 2>/dev/null
            mv "$itp.tmp" "$itp" 2>/dev/null || true
        fi
    done

    echo "TOPOL: Complete"
}

# ── Box definition ──
run_stage_box() {
    local out="output/setup/box.gro"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    echo "BOX: Creating $BOX_TYPE box..."
    $GMX editconf \
        -f output/setup/processed.gro \
        -o "$out" \
        -bt "$BOX_TYPE" \
        -d "$BOX_DISTANCE"

    [ -f "$out" ] || { echo "ERROR: editconf failed"; exit 1; }
    echo "BOX: Complete"
}

# ── Solvation ──
run_stage_solvate() {
    local out="output/setup/solv.gro"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    echo "SOLVATE: Adding water..."
    $GMX solvate \
        -cp output/setup/box.gro \
        -cs spc216.gro \
        -o "$out" \
        -p output/setup/topol.top

    [ -f "$out" ] || { echo "ERROR: solvate failed"; exit 1; }
    echo "SOLVATE: Complete"
}

# ── Ion addition ──
run_stage_ions() {
    local out="output/setup/ions.gro"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    echo "IONS: Adding ions..."
    mkdir -p output/setup

    $GMX grompp \
        -f mdp/em.mdp \
        -c output/setup/solv.gro \
        -r output/setup/solv.gro \
        -p output/setup/topol.top \
        -o output/setup/ions.tpr \
        -maxwarn 2

    echo "SOL" | $GMX genion \
        -s output/setup/ions.tpr \
        -o "$out" \
        -p output/setup/topol.top \
        -pname "$CATION" \
        -nname "$ANION" \
        -neutral \
        -conc "$SALT_CONC"

    [ -f "$out" ] || { echo "ERROR: genion failed"; exit 1; }
    echo "IONS: Complete"
}

# ── Index file creation ──
# Uses GROMACS' default index groups and combines them dynamically
# into the groups expected by the MDP temperature coupling lines
# (tc-grps = Protein_DNA Water_Ions).
#
# Rather than hardcoding group numbers (which vary by system), this
# function determines the current maximum group number from make_ndx
# output and assigns the next two numbers to the new groups.
run_stage_index() {
    local out="output/setup/index.ndx"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    echo "INDEX: Creating temperature coupling groups..."

    # Verify the auto-generated 'Water' and 'Ion' groups exist before
    # building selections. GROMACS creates them after solvation (solv.gro)
    # and ion addition (ions.gro). If either is missing, the selections
    # below would silently be wrong.
    local check
    check=$($GMX select -s output/setup/ions.gro \
        -select 'group Water; group Ion' -on "$out.check" 2>&1)
    rm -f "$out.check"
    if echo "$check" | grep -q "no such index group\|Cannot match"; then
        echo "ERROR: Required index groups 'Water' or 'Ion' not found."
        echo "       These are auto-generated by GROMACS after solvation"
        echo "       and ion addition. Check that output/setup/solv.gro"
        echo "       and output/setup/ions.gro exist and were created."
        exit 1
    fi

    # Generate the two temperature-coupling groups with gmx select.
    # Group names are expression-derived (deterministic), so we rename
    # them afterwards to the names the MDP tc-grps expect.
    $GMX select -s output/setup/ions.gro -on "$out" \
        -select 'not (group Water or group Ion); group Water or group Ion'

    [ -f "$out" ] || { echo "ERROR: index generation failed"; exit 1; }

    # Rename expression-derived group names to MDP-expected names
    awk '
    /^\[/ {
        if ($0 == "[ not_(group_Water_or_group_Ion) ]") print "[ Protein_DNA ]"
        else if ($0 == "[ group_Water_or_group_Ion ]") print "[ Water_Ions ]"
        else print
        next
    }
    { print }
    ' "$out" > "$out.tmp"
    mv "$out.tmp" "$out"

    # Verify the renamed groups exist
    if ! grep -q "Protein_DNA" "$out"; then
        echo "ERROR: Protein_DNA group not found after renaming."
        exit 1
    fi
    if ! grep -q "Water_Ions" "$out"; then
        echo "ERROR: Water_Ions group not found after renaming."
        exit 1
    fi

    echo "INDEX: Complete"
}

# ── Run grompp with strict warning verification ──
# Runs gmx grompp, then inspects every warning. Only the two known benign
# warnings are tolerated:
#   1. free ions not bound by a potential/constraint
#   2. COM removal in the presence of position restraints
# Any other warning, or grompp failure, exits with a clear error.
# Usage: run_grompp_checked <maxwarn> <grompp args...>
run_grompp_checked() {
    local maxwarn="$1"
    shift

    local log
    log=$(mktemp)

    $GMX grompp -maxwarn "$maxwarn" "$@" > "$log" 2>&1
    local rc=$?

    if [ "$rc" -ne 0 ]; then
        echo "ERROR: grompp failed:"
        grep -E 'Fatal|Error|NOTE|WARNING' "$log" 2>/dev/null | head -10
        rm -f "$log"
        exit 1
    fi

    # Inspect every warning block and verify it is expected
    local block="" bad=0
    while IFS= read -r line; do
        case "$line" in
            "NOTE "*|"WARNING "*)
                if [ -n "$block" ]; then
                    case "$block" in
                        *"not bound by a potential or constraint"*) ;;
                        *"Removing center of mass motion"*) ;;
                        *) echo "ERROR: Unexpected grompp warning:"; echo "$block"; bad=1 ;;
                    esac
                fi
                block="$line"
                ;;
            "  "*)
                [ -n "$block" ] && block="$block
$line"
                ;;
        esac
    done < "$log"

    if [ -n "$block" ]; then
        case "$block" in
            *"not bound by a potential or constraint"*) ;;
            *"Removing center of mass motion"*) ;;
            *) echo "ERROR: Unexpected grompp warning:"; echo "$block"; bad=1 ;;
        esac
    fi

    rm -f "$log"
    if [ "$bad" -ne 0 ]; then
        echo "       If this warning is expected for your system, review"
        echo "       the MDP and topology before proceeding."
        exit 1
    fi
}

# ── Energy minimization ──
run_stage_em() {
    local out="output/equilibration/em.gro"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    mkdir -p output/equilibration
    echo "EM: Energy minimization..."

    run_grompp_checked 0 \
        -f mdp/em.mdp \
        -c output/setup/ions.gro \
        -r output/setup/ions.gro \
        -p output/setup/topol.top \
        -n output/setup/index.ndx \
        -o output/equilibration/em.tpr

    $GMX mdrun \
        -deffnm output/equilibration/em \
        -v

    if [ ! -f "$out" ]; then
        echo "ERROR: EM failed to produce $out"
        exit 1
    fi

    # Verify convergence: GROMACS writes "converged to Fmax" to the log
    # when the minimization reaches the force tolerance (emtol).
    # The output .gro file is written even without convergence, so file
    # existence alone is insufficient.
    if ! grep -qi "converged" output/equilibration/em.log 2>/dev/null; then
        echo "ERROR: Energy minimization did not converge."
        echo "       Check output/equilibration/em.log for details."
        exit 1
    fi
    echo "EM: Converged"
}

# ── NVT equilibration ──
run_stage_nvt() {
    local out="output/equilibration/nvt.gro"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    echo "NVT: Temperature equilibration..."

    run_grompp_checked 2 \
        -f mdp/nvt.mdp \
        -c output/equilibration/em.gro \
        -r output/equilibration/em.gro \
        -p output/setup/topol.top \
        -n output/setup/index.ndx \
        -o output/equilibration/nvt.tpr

    local gpu_flags
    gpu_flags=$(gmx_gpu_flags)

    $GMX mdrun \
        -deffnm output/equilibration/nvt \
        -cpi output/equilibration/nvt.cpt \
        $gpu_flags \
        -v

    if [ ! -f "$out" ]; then
        echo "ERROR: NVT failed to produce $out"
        exit 1
    fi
    echo "NVT: Complete"
}

# ── NPT equilibration ──
run_stage_npt() {
    local out="output/equilibration/npt.gro"
    [ -f "$out" ] && { echo "SKIP: $out exists"; return 0; }

    echo "NPT: Pressure equilibration..."

    run_grompp_checked 2 \
        -f mdp/npt.mdp \
        -c output/equilibration/nvt.gro \
        -r output/equilibration/nvt.gro \
        -t output/equilibration/nvt.cpt \
        -p output/setup/topol.top \
        -n output/setup/index.ndx \
        -o output/equilibration/npt.tpr

    local gpu_flags
    gpu_flags=$(gmx_gpu_flags)

    $GMX mdrun \
        -deffnm output/equilibration/npt \
        -cpi output/equilibration/npt.cpt \
        $gpu_flags \
        -v

    if [ ! -f "$out" ]; then
        echo "ERROR: NPT failed to produce $out"
        exit 1
    fi
    echo "NPT: Complete"
}

# ── Production MD (checkpoint-aware, used for all chunks) ──
run_stage_production() {
    echo "PRODUCTION: Running production MD..."
    mkdir -p output/production

    if [ ! -f output/production/md.tpr ]; then
        echo "PRODUCTION: Compiling TPR..."
        run_grompp_checked 2 \
            -f mdp/md.mdp \
            -c output/equilibration/npt.gro \
            -r output/equilibration/npt.gro \
            -p output/setup/topol.top \
            -n output/setup/index.ndx \
            -o output/production/md.tpr
    fi

    # Calculate maxh from walltime with 10% safety margin
    local walltime_seconds
    walltime_seconds=$(echo "$PROD_WALLTIME" | awk -F: '{print ($1*3600 + $2*60 + $3) * 0.9}')
    local maxh
    maxh=$(echo "scale=2; $walltime_seconds / 3600" | bc 2>/dev/null || echo "23.5")

    local gpu_flags
    gpu_flags=$(gmx_gpu_flags)

    # -append requires an existing checkpoint. On the first chunk there is
    # none, so only enable append when resuming from a prior chunk.
    local append_flag=""
    [ -f output/production/md.cpt ] && append_flag="-append"

    echo "PRODUCTION: mdrun -maxh $maxh"
    $GMX mdrun \
        -deffnm output/production/md \
        -cpi output/production/md.cpt \
        $append_flag \
        -maxh "$maxh" \
        -nsteps -1 \
        $gpu_flags \
        -v

    echo "PRODUCTION: mdrun exited (checkpoint written if walltime exceeded)"
}
